apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-html-app
spec:
  replicas: 2 # Ensure at least two instances are running
  selector:
    matchLabels:
      app: my-html-app
  template:
    metadata:
      labels:
        app: my-html-app
    spec:
      containers:
        - name: my-html-container
          image: my-html-app:v1.0  # Placeholder, will be updated by Jenkins
          ports:
            - containerPort: 80
