apiVersion: v1
kind: Service
metadata:
  name: my-html-service
spec:
  type: NodePort
  selector:
    app: my-html-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # Example NodePort
